---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: restart tickertape services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
  become: true
  loop:
    - tickertape.service
    - tickertape-worker.service
